### PR TITLE
Spec 334: Preserve spaces in inline code blocks consisting of spaces only

### LINKED ISSUE #243: failing verificaiton of spec unit 334: don't strip spaces when code span only contains spaces
Failing example:

```
` `
`  `
.
<p><code> </code>
<code>  </code></p>
```

for requirement

> No stripping occurs if the code span contains only spaces:

https://github.com/madroach/omd/blob/master/tests/spec.txt#L5923-L5931

Required for #235

### PR DESCRIPTION
**Pull request by sonologico**
Fixes #243

### CODE REVIEW

File: src/compat.ml [hunk 1]
```diff
@@ -44,3 +44,15 @@ module Buffer = struct
         Buffer.add_char b (Char.unsafe_chr (0x80 lor (u land 0x3F)))
     | _ -> assert false
 end
+
+module String = struct
+  include String
+
+  let for_all p s =
```
Comment (sonologico) [inline src/compat.ml:51]: `String.for_all` is available from `4.13.0`. This is copied from the stdlib.

**Review by shonfeder — APPROVED** [review]
LGTM! :tada:
